version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    profiles:
      - jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 4317:4317
      - 4318:4318
      - 5778:5778
      - 16686:16686
      - 14268:14268
      #- 9411:9411
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - unir_tracing
    restart: unless-stopped

  zipkin:
    profiles:
      - zipkin
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - unir_tracing
    restart: unless-stopped

networks:
  unir_tracing:
    driver: bridge