server:
  port: 8082


spring:
  application:
    name: books
  datasource:
    url: jdbc:h2:mem:orders
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

management:
  tracing:
    sampling:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

