server:
  port: 8081

spring:
  application:
    name: requests
  datasource:
    url: jdbc:h2:mem:orders
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

tracing:
  url: http://localhost:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


